config/routes.rb
Rails.application.routes.draw do
  get 'rate/index'
  get 'rate', to: 'rate#index'
  get 'rate/load'
  post 'rate/load'
  root to: 'converter#index'
  get 'converter/index'
  post 'converter/convert'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/converter.rb
class Converter
    include ActiveModel::Validations

    validates :type, presence: true
    validates :amount, presence: true, numericality: { only_integer: true, greater_than: 0 }
    validates :from, presence: true
    validates :to, presence: true
    validates_with ConverterValidator
    
    attr_accessor :type, :amount, :from, :to

    WEB_SOURCE = 'https://www.nbrb.by/api/exrates/rates?periodicity=0'
    FILE_PATH = Rails.root.join('app', 'storage')

    def initialize(params = {})
      params.each {|name, value| send("#{name}=", value)}     
    end

    def call(params)                  
      con = Converter::CurrencyConverter.new(get_data(params[:type]))
      # byebug
      result = con.convert(params[:amount].to_i, params[:from], params[:to])
      result = "#{ result[1].cents } cents | #{ con.format_convert(*result) }"
    end    

    def get_data(type)
      if type == 'DB'
        result = {}
        Rate.all.each {|cur| result[cur.abbreviation] = {
          'Cur_Scale' => cur.scale, 
          'Cur_name' => cur.name,
          'Cur_OfficialRate' => cur.rate}}
        result
      else  
        data_source = type == 'web' ? WEB_SOURCE : "#{FILE_PATH}/data.#{type}"
        data_clazz = Converter::DataFactory.for(type)
        data_clazz.get_data(data_source)
      end
    end
end

app/models/converter_caller.rb
class ConverterCaller
    include ActiveModel::Validations
    validates :type, presence: true
    validates :amount, presence: true, numericality: { only_integer: true, greater_than: 0 }
    validates :from, presence: true
    validates :to, presence: true
    validates_with ConverterValidator
    
    attr_accessor :type, :amount, :from, :to

    WEB_SOURCE = 'https://www.nbrb.by/api/exrates/rates?periodicity=0'
    FILE_PATH = Rails.root.join('app', 'storage')

    def initialize(params = {})
      params.each {|name, value| send("#{name}=", value)}      
    end

    def call(params)      
      # validates :params[:amount], presense: true, numericality: {only_integer: true}
      data_source = params[:type] == 'web' ? WEB_SOURCE : "#{FILE_PATH}/data.#{params[:type]}"
      data_clazz = DataFactory.for(params[:type])       
      con = CurrencyConverter.new(data_clazz.get_data(data_source))
      # byebug
      con.convert(params[:amount].to_i, params[:from], params[:to])[1].cents
    end
end

app/models/converter_validator.rb
class ConverterValidator < ActiveModel::Validator
  def validate(record)
    if (record.amount.to_i) < 100
      record.errors.add :amount, :is_too_small
    end
  end
end

app/models/rate.rb
# == Schema Information
#
# Table name: rates
#
#  id           :integer          not null, primary key
#  abbreviation :string
#  name         :string
#  rate         :float
#  scale        :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
# Indexes
#
#  index_rates_on_name  (name) UNIQUE
#
class Rate < ApplicationRecord 
  
  def self.fill_data
    data_clazz = Converter::DataFactory.for('web')       
    data = data_clazz.get_data(WEB_SOURCE)
    data.each do |cur, attr|
      Rate.create(
        abbreviation: cur, 
        name: attr['Cur_Name'],
        rate: attr['Cur_OfficialRate'],
        scale: attr['Cur_Scale']        
      )
    end
  end

  def self.load
    ActiveRecord::Base.transaction do
      Rate.delete_all
      Converter::DataUtils.get_raw_json(ENV['WEB_SOURCE']).each do |cur|
        Rate.create(
          name: cur['Cur_Name'],
          abbreviation: cur['Cur_Abbreviation'],
          scale: cur['Cur_Scale'],
          rate: cur['Cur_OfficialRate']
        )
      end
    end
  rescue ArgumentError, SocketError, Errno::ENOENT, JSON::ParserError => e
    puts(e)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/converter_controller.rb
class ConverterController < ApplicationController

  def index    
    @converter = Converter.new     
  end

  def convert
    @params = params.require(:converter).permit(:type, :amount, :from, :to)    
=begin
    respond_to do |format|
      format.js 
    end
=end
    @converter = Converter.new(@params)
    if @converter.valid?
      @result = @converter.call(@params) 
    else
      @result = @converter.errors.messages.inject('') {|out, msg| out + msg[1].join(' | ') + '\n' }
    end 
    ActionCable.server.broadcast('currency_news', result: @result, time: Time.current)
  end
end

app/controllers/rate_controller.rb
class RateController < ApplicationController
  def index
  end

  def load
    Rate.load
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/converter_helper.rb
module ConverterHelper
end

app/helpers/rate_helper.rb
module RateHelper
end

app/views/converter/convert.js.slim
| document.getElementById("result").innerHTML = "#{ @result }"

app/views/converter/index.html.slim
h3
  | Приложение для конверсии валют
.col-md-8
  = form_with model: @converter, url: converter_convert_path do |f|
    .form-group
      = f.label(:type, "Тип источника данных")
      = f.select :type, options_for_select([ \
        ['взять из БД', 'DB'], \
        ['Web API', 'web'], \
        ['файл *.json ','json'], \
        ['файл *.csv', 'csv']])        
    .form-group
      = f.label(:amount, "Сумма")
      = f.number_field :amount
    .form-group
      = f.label(:from, "Исходная валюта")        
      = f.text_field :from
    .form-group
      = f.label(:to, "Конвертировать в")  
      = f.text_field :to
    = submit_tag("Конвертировать")
div
  h3
    pre#result
div
  h4 Произведенные конверсии:
  h5#broadcast    

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Converter
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = yield

app/views/rate/index.html.slim
h3 Загрузка актуальных курсов валют в базу с сайта nbrb.by
= form_with url: rate_load_path 
  = submit_tag 'Загрузить'

app/views/rate/load.html.slim
h1 Rate#load
p Find me in app/views/rate/load.html.slim